version: '3.8'
services:
  webhook:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - ./uploads:/app/uploads
    environment:
      - VAULT_ADDR
      - VAULT_TOKEN  
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    